#pragma once

#ifdef __cplusplus
extern "C" {
#endif
#include "tolua++.h"
#ifdef __cplusplus
}
#endif

enum
{
#if (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)
    VK_LBUTTON = 0x1001,
    VK_RBUTTON,
    VK_CANCEL,
    VK_MBUTTON,
    VK_XBUTTON1,
    VK_XBUTTON2,
    VK_BACK,
    VK_TAB,
    VK_CLEAR,
    VK_RETURN,
    VK_SHIFT,
    VK_CONTROL,
    VK_MENU,
    VK_PAUSE,
    VK_CAPITAL,
    VK_KANA,
    VK_HANGEUL,
    VK_HANGUL,
    VK_JUNJA,
    VK_FINAL,
    VK_HANJA,
    VK_KANJI,
    VK_ESCAPE,
    VK_CONVERT,
    VK_NONCONVERT,
    VK_ACCEPT,
    VK_MODECHANGE,
    VK_SPACE,
    VK_PRIOR,
    VK_NEXT,
    VK_END,
    VK_HOME,
    VK_LEFT,
    VK_UP,
    VK_RIGHT,
    VK_DOWN,
    VK_SELECT,
    VK_PRINT,
    VK_EXECUTE,
    VK_SNAPSHOT,
    VK_INSERT,
    VK_DELETE,
    VK_HELP,
    VK_LWIN,
    VK_RWIN,
    VK_APPS,
    VK_SLEEP,
    VK_NUMPAD0,
    VK_NUMPAD1,
    VK_NUMPAD2,
    VK_NUMPAD3,
    VK_NUMPAD4,
    VK_NUMPAD5,
    VK_NUMPAD6,
    VK_NUMPAD7,
    VK_NUMPAD8,
    VK_NUMPAD9,
    VK_MULTIPLY,
    VK_ADD,
    VK_SEPARATOR,
    VK_SUBTRACT,
    VK_DECIMAL,
    VK_DIVIDE,
    VK_F1,
    VK_F2,
    VK_F3,
    VK_F4,
    VK_F5,
    VK_F6,
    VK_F7,
    VK_F8,
    VK_F9,
    VK_F10,
    VK_F11,
    VK_F12,
    VK_F13,
    VK_F14,
    VK_F15,
    VK_F16,
    VK_F17,
    VK_F18,
    VK_F19,
    VK_F20,
    VK_F21,
    VK_F22,
    VK_F23,
    VK_F24,
    VK_NUMLOCK,
    VK_SCROLL,
    VK_OEM_NEC_EQUAL,
    VK_OEM_FJ_JISHO,
    VK_OEM_FJ_MASSHOU,
    VK_OEM_FJ_TOUROKU,
    VK_OEM_FJ_LOYA,
    VK_OEM_FJ_ROYA,
    VK_LSHIFT,
    VK_RSHIFT,
    VK_LCONTROL,
    VK_RCONTROL,
    VK_LMENU,
    VK_RMENU,
    VK_BROWSER_BACK,
    VK_BROWSER_FORWARD,
    VK_BROWSER_REFRESH,
    VK_BROWSER_STOP,
    VK_BROWSER_SEARCH,
    VK_BROWSER_FAVORITES,
    VK_BROWSER_HOME,
    VK_VOLUME_MUTE,
    VK_VOLUME_DOWN,
    VK_VOLUME_UP,
    VK_MEDIA_NEXT_TRACK,
    VK_MEDIA_PREV_TRACK,
    VK_MEDIA_STOP,
    VK_MEDIA_PLAY_PAUSE,
    VK_LAUNCH_MAIL,
    VK_LAUNCH_MEDIA_SELECT,
    VK_LAUNCH_APP1,
    VK_LAUNCH_APP2,
    VK_OEM_1,
    VK_OEM_PLUS,
    VK_OEM_COMMA,
    VK_OEM_MINUS,
    VK_OEM_PERIOD,
    VK_OEM_2,
    VK_OEM_3,
    VK_OEM_4,
    VK_OEM_5,
    VK_OEM_6,
    VK_OEM_7,
    VK_OEM_8,
    VK_OEM_AX,
    VK_OEM_102,
    VK_ICO_HELP,
    VK_ICO_00,
    VK_PROCESSKEY,
    VK_ICO_CLEAR,
    VK_PACKET,
    VK_OEM_RESET,
    VK_OEM_JUMP,
    VK_OEM_PA1,
    VK_OEM_PA2,
    VK_OEM_PA3,
    VK_OEM_WSCTRL,
    VK_OEM_CUSEL,
    VK_OEM_ATTN,
    VK_OEM_FINISH,
    VK_OEM_COPY,
    VK_OEM_AUTO,
    VK_OEM_ENLW,
    VK_OEM_BACKTAB,
    VK_ATTN,
    VK_CRSEL,
    VK_EXSEL,
    VK_EREOF,
    VK_PLAY,
    VK_ZOOM,
    VK_NONAME,
    VK_PA1,
    VK_OEM_CLEAR,
    WM_LBUTTONDOWN,
    WM_LBUTTONUP,
    WM_LBUTTONDBLCLK,
    WM_RBUTTONDOWN,
    WM_RBUTTONUP,
    WM_RBUTTONDBLCLK,
    WM_MBUTTONDOWN,
    WM_MBUTTONUP,
    WM_MBUTTONDBLCLK,
    WM_MOUSEWHEEL,
    WM_XBUTTONDOWN,
    WM_XBUTTONUP,
    WM_XBUTTONDBLCLK,
    WM_MOUSEHWHEEL,
    WM_MOUSELAST,
    WHEEL_DELTA,
#endif
	VK_0					= 0x30,
	VK_1					= 0x31,
	VK_2					= 0x32,
	VK_3					= 0x33,
	VK_4					= 0x34,
	VK_5					= 0x35,
	VK_6					= 0x36,
	VK_7					= 0x37,
	VK_8					= 0x38,
	VK_9					= 0x39,
	VK_A					= 0x41,
	VK_B					= 0x42,
	VK_C					= 0x43,
	VK_D					= 0x44,
	VK_E					= 0x45,
	VK_F					= 0x46,
	VK_G					= 0x47,
	VK_H					= 0x48,
	VK_I					= 0x49,
	VK_J					= 0x4A,
	VK_K					= 0x4B,
	VK_L					= 0x4C,
	VK_M					= 0x4D,
	VK_N					= 0x4E,
	VK_O					= 0x4F,
	VK_P					= 0x50,
	VK_Q					= 0x51,
	VK_R					= 0x52,
	VK_S					= 0x53,
	VK_T					= 0x54,
	VK_U					= 0x55,
	VK_V					= 0x56,
	VK_W					= 0x57,
	VK_X					= 0x58,
	VK_Y					= 0x59,
	VK_Z					= 0x5A,
};

TOLUA_API int tolua_LuaExtern_open(lua_State* tolua_S);

TOLUA_API int tolua_LuaExternHandler_open(lua_State* tolua_S);

